# Generated by Django 4.2.7 on 2024-07-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data_hora',
            new_name='data_hora_created',
        ),
        migrations.AddField(
            model_name='venda',
            name='data_hora_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
